server:  
  build: .
  ports: 
    - 8088:8088
  volumes:
    - ./server:/go/src/github.com/pascallimeux/urmmongo
  links:
    - database
  environment:
    - DB_NAME=MHT2015DBBIS

database:  
  image: mongo:3.0
  command: mongod --smallfiles --quiet --logpath=/dev/null