USER="pascal"
SRCPATH="$GOPATH/src/github.com/pascallimeux/urmmongo2"
DATAREPO="/data"
SRCBIN="$DATAREPO/urmmongo2/dist"
LOGDIR="$SRCBIN/logs"
export URMMONGOPATH="$SRCBIN"
export URMMONGOLOGFILE="$LOGDIR/urmmongo.log"
export URMMONGOCONFIGFILE="$SRCBIN/config.json"